spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
server.port=8080
cloud.aws.credentials.access-key=${AWS_ACCESS_KEY}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY}
cloud.aws.region.static=${AWS_REGION}
aws.bucket.name=${AWS_BUCKET_NAME}
minio.endpoint=${MINIO_ENDPOINT:unused}
minio.public.endpoint=${MINIO_PUBLIC_ENDPOINT:unused}
ses.access.key=${SES_ACCESS_KEY}
ses.secret.key=${SES_SECRET_KEY}
ses.region=${AWS_SES_REGION}
ses.from.email=${SES_FROM_EMAIL}
app.frontend.url=https://expense-tracker-frontend-beryl-two.vercel.app
logging.level.com.example.springbootmvcexample=INFO
