cloud.aws.credentials.access-key=${AWS_ACCESS_KEY:dummy}
cloud.aws.credentials.secret-key=${AWS_SECRET_KEY:dummy}
cloud.aws.region.static=${AWS_REGION:us-east-1}
aws.bucket.name=${AWS_BUCKET_NAME:nanibabu123}


!--> We have set default values for AWS credentials and bucket name to "dummy" and "nanibabu123" respectively. You should replace these with your actual AWS credentials and bucket name when running the application locally.
!!--> This file is used to override the default properties for local development. Make sure to keep this file secure and do not commit it to version control if it contains sensitive information.
!--> We changed the credential values in S3Config.java, S3Service.java and S3Controller.java to use the values from this properties file instead of hardcoding them. This allows us to easily switch between different environments (local, staging, production) by simply changing the properties file without modifying the code.